version: '3'
services:
  angular-app:
    build: /home/jenkins/angular
    ports:
      - "4200:4200"
    networks:
      - app-network
  node-app:
    build: /home/jenkins/node
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge