version: '3'
services:
  angular-app:
    build: ./angular-project
    ports:
      - "4200:80"
    networks:
      - app-network
  node-app:
    build: ./node-project
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge