version: '3'
services:
  angular-app:
    build:
      context: /home/jenkins/angular
    ports:
      - "4200:80"
    networks:
      - app-network

  node-app:
    build:
      context: /home/jenkins/node
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
